### ISSUE TITLE
Can this decoding method be directly used in the question answering task? For example chatgpt

### ISSUE THREAD

**Issue by lawo123** [jaymody/speculative-sampling#6]

**Comment by jaymody** [comment]
Speculative sampling is agnostic to the task, so yes it will work with question answering. It's just a technique to speed up decodes times for GPT models. You could use it on a GPT that predicts the next pixel in an image, that task at hand doesn't matter (as long as the acceptance rate is high enough, and the draft model is fast enough, it should yield a speedup).
